## 4. 矩阵的定义与表示

### 矩阵的定义

一个m × n的矩阵可以表示为：$$ A = \begin{pmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \
a_{21} & a_{22} & \cdots & a_{2n} \
\vdots & \vdots & \ddots & \vdots \
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{pmatrix} $$

### 矩阵的类型

- 行矩阵：只有一行的矩阵，形如1 × n。
- 列矩阵：只有一列的矩阵，形如m × 1。
- 方阵：行数和列数相等的矩阵，形如n × n。
- 零矩阵：所有元素均为零的矩阵。
- 单位矩阵：对角线上为1，其他元素为0的方阵，通常用I_n表示。

### 矩阵的表示

1. 文本表示：
2. LaTeX 表示：

### 组成矩阵的元素

矩阵的元素可以是任何类型的数据，如整数、浮点数，甚至是更复杂的数据类型。在实际应用中，我们主要关注浮点数矩阵，因为它们用于表示图像、音频等各种数据。

### 案例：图像处理中的矩阵

在图像处理中，彩色图片通常可以表示为一个3D矩阵。例如，一张宽为W、高为H的RGB图像可以表示为一个H × W × 3的矩阵，其中3对应红、绿、蓝三种颜色通道。每个元素代表通道的取值（通常在0到255之间）。

可以用Python的NumPy库进行矩阵操作:

In [1]:
import numpy as np

# 创建一个 2行 3列的矩阵
A = np.array([[1, 2, 3],
              [4, 5, 6]])

print("矩阵 A:")
print(A)

# 创建一个 2 × 2 的单位矩阵
I = np.eye(2)
print("单位矩阵 I:")
print(I)

矩阵 A:
[[1 2 3]
 [4 5 6]]
单位矩阵 I:
[[1. 0.]
 [0. 1.]]


### 矩阵的维度与形状

In [2]:
print("矩阵 A 的形状:", A.shape)  # 输出: (2, 3)

矩阵 A 的形状: (2, 3)
