## 7. 矩阵的转置与逆

### 矩阵的转置(Transpose)

矩阵的转置是以对角线为轴的镜像，这条从左上角到右下角的对角线被称为 **主对角线**（main diagonal）。

#### 定义

一个矩阵的转置是通过将矩阵的行和列互换来得到的新矩阵。对于一个矩阵 $ A $，如果 $ A $ 的大小为 $ m \times n $，则其转置 $ A^T $ 的大小为 $ n \times m $。具体来说，如果:

$$ A = \begin{pmatrix} a_{11} & a_{12} & \cdots & a_{1n} \\
                       a_{21} & a_{22} & \cdots & a_{2n} \\
                       \vdots & \vdots & \ddots & \vdots \\
                       a_{m1} & a_{m2} & \cdots & a_{mn} \end{pmatrix} \quad

则其转置为：

   A^T = \begin{pmatrix} a_{11} & a_{21} & \cdots & a_{m1} \\
                         a_{12} & a_{22} & \cdots & a_{m2} \\
                         \vdots & \vdots & \ddots & \vdots \\
                         a_{1n} & a_{2n} & \cdots & a_{mn} \end{pmatrix} $$

#### 性质

1. 双重转置：$ (A^T)^T = A $ 。
2. 转置的和：$ (A + B)^T = A^T + B^T $ 。
3. 转置的乘法：$ (AB)^T = B^T A^T $ 。

#### 例子

$$ A = \begin{pmatrix} 1 & 2 \\
                       3 & 4 \end{pmatrix} \quad
则其转置为：
   A^T = \begin{pmatrix} 1 & 3 \\
                         2 & 4 \end{pmatrix} $$

In [4]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
A_transpose = A.T

print("原矩阵 A:\n", A)
print("转置矩阵 A^T:\n", A_transpose)

原矩阵 A:
 [[1 2]
 [3 4]]
转置矩阵 A^T:
 [[1 3]
 [2 4]]


### 矩阵的逆（Matrix Inversion）

#### 单位矩阵（Identity Matrix）
任意向量和单位矩阵相乘，都不会改变。我们将保持 $ n $ 维向量不变的单位矩阵记作 $ I_n $。  
形式上，
$$ I_n \in \mathbb{R}^{n×n}，\quad \forall{x} \in \mathbb{R}^n, \quad I_nx = x. $$

单位矩阵的结构很简单：所有沿主对角线的元素都是 1，而所有其他位置的元素都是0。如:
$$ \begin{pmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{pmatrix} $$

#### 矩阵的逆定义

一个可逆矩阵（或称为非奇异矩阵）是指一个方阵 $ A $ 存在一个矩阵 $ B $，使得 $ AB = BA = I $，其中 $ I $ 是单位矩阵。在这种情况下，我们称 $ B $ 为 $ A $ 的逆矩阵，通常记作 $ A^{-1} $。

#### 性质

1. 唯一性: 若矩阵 $ A $ 可逆，则其逆矩阵 $ A^{-1} $ 唯一。
2. 逆的乘法: $ (AB)^{-1} = B^{-1} A^{-1} $。
3. 逆的转置: $ (A^T)^{-1} = (A^{-1})^T $。

#### 逆矩阵计算
$$ A^{-1} = \frac{1}{det(A)}adj(A) $$ 
$$ A = \begin{pmatrix} a & b \\ c & d \end{pmatrix} 
   \implies det(A) = ac -bd $$

#### $ adj(V) $伴随矩阵（Adjugate Matrix）
##### 1. 伴随矩阵的定义  
伴随矩阵是原矩阵的代数余子式矩阵的转置。即，对矩阵 $ V $ 的每个元素 $ a_{ij} $，我们计算它的代数余子式 $ C_{ij} $，然后将代数余子式矩阵进行转置，得到伴随矩阵 $ adj(V) $。

- 余子式(Cofactors)：对矩阵 $ V $ 的每个元素 $ a_{ij} $，去掉它所在的行和列，剩下的子矩阵的行列式叫做 $ a_{ij} $ 的余子式，记作 $ M_{ij} $。
- 代数余子式(Algebraic Cofactors)：代数余子式 $ C_{ij} $ 是余子式 $ M_{ij} $ 乘以一个符号因子，该因子为 $ (-1)^{i+j} $（这取决于元素的行列索引）。
  $$ C_{ij} = (-1)^{i+j}M_{ij} $$

##### 2. 伴随矩阵的计算步骤
- 计算余子式：对矩阵 $ V $ 中的每个元素 $ a_{ij} $，去掉它所在的行和列，计算剩余矩阵的行列式（这是它的余子式）。
- 加上符号：根据 $ (-1)^{i+j} $ 的符号，对每个余子式进行符号调整，得到代数余子式。
- 转置：将代数余子式矩阵进行转置，得到伴随矩阵。

**例子**

$$ V = \begin{pmatrix} a & b \\ c & d \end{pmatrix} $$

计算伴随矩阵步骤：  
1. 计算余子式：
- 对 $ a $ 来说，去掉第 $ 1 $ 行第 1 列，剩余矩阵为 $ d $，所以余子式为 $ M_{11} = d $
- 对 $ b $ 来说，去掉第 $ 1 $ 行第 2 列，剩余矩阵为 $ c $，所以余子式为 $ M_{12} = c $​
- 对 $ c $ 来说，去掉第 $ 2 $ 行第 1 列，剩余矩阵为 $ b $，所以余子式为 $ M_{21} = b $​
- 对 $ d $ 来说，去掉第 $ 2 $ 行第 2 列，剩余矩阵为 $ a $，所以余子式为 $ M_{22} = a $​

2. 加上符号：
- 对于 $ a $，代数余子式为: $ C_{11} = (-1)^{1+1} \times d $
- 对于 $ b $，代数余子式为: $ C_{12} = (-1)^{1+2} \times c $
- 对于 $ c $，代数余子式为: $ C_{21} = (-1)^{2+1} \times b $
- 对于 $ d $，代数余子式为: $ C_{22} = (-1)^{2+2} \times a $

3. 转置:   
   代数余子式为：$ \begin{pmatrix} d & -c \\ -b & a \end{pmatrix} $

   转置之后得到伴随矩阵：$ adj(V) = \begin{pmatrix} d & -b \\ -c & a \end{pmatrix} $


对于 $ 2×2 $ 矩阵 $ A $，其伴随矩阵可以通过以下公式直接计算得到：
$$ A = \begin{pmatrix} a & b \\ c & d \end{pmatrix}  
   \implies adj(A) = \begin{pmatrix} d & -b \\ -c & a \end{pmatrix} $$

通过交换主对角线上的元素 $ a $ 和 $ d $，并将副对角线上的元素 $ b $ 和 $ c $ 取反得到的。

#### 例子

$$ A = \begin{pmatrix} 4 & 7 \\
                       2 & 6 \end{pmatrix} \quad
   计算行列式判断其是否可逆：
   \text{det}(A) = 4 \cdot 6 - 7 \cdot 2 = 24 - 14 = 10 \neq 0
                       $$

行列式不为零，矩阵 $ A $ 可逆。

$$ A^{-1} = \frac{1}{\text{det}(A)} \begin{pmatrix} d & -c \\
                                                    -b & a \end{pmatrix} 
          = \frac{1}{10} \begin{pmatrix} 6 & -7 \\
                                        -2 & 4 \end{pmatrix} 
          = \begin{pmatrix} 0.6 & -0.7 \\
                           -0.2 & 0.4 \end{pmatrix} $$

In [2]:
import numpy as np

A = np.array([[4, 7], [2, 6]])
A_inv = np.linalg.inv(A)

print("原矩阵 A:\n", A)
print("逆矩阵 A^{-1}:\n", A_inv)

原矩阵 A:
 [[4 7]
 [2 6]]
逆矩阵 A^{-1}:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
