## 7. 矩阵的转置与逆

### 矩阵的转置

#### 定义

一个矩阵的转置是通过将矩阵的行和列互换来得到的新矩阵。对于一个矩阵 $ A $，如果 $ A $ 的大小为 $ m \times n $，则其转置 $ A^T $ 的大小为 $ n \times m $。具体来说，如果:

$$ A = \begin{pmatrix} a_{11} & a_{12} & \cdots & a_{1n} \\
                       a_{21} & a_{22} & \cdots & a_{2n} \\
                       \vdots & \vdots & \ddots & \vdots \\
                       a_{m1} & a_{m2} & \cdots & a_{mn} \end{pmatrix} \quad

则其转置为：

   A^T = \begin{pmatrix} a_{11} & a_{21} & \cdots & a_{m1} \\
                         a_{12} & a_{22} & \cdots & a_{m2} \\
                         \vdots & \vdots & \ddots & \vdots \\
                         a_{1n} & a_{2n} & \cdots & a_{mn} \end{pmatrix} $$

#### 性质

1. 双重转置：$ (A^T)^T = A $ 。
2. 转置的和：$ (A + B)^T = A^T + B^T $ 。
3. 转置的乘法：$ (AB)^T = B^T A^T $ 。

#### 例子

$$ A = \begin{pmatrix} 1 & 2 \\
                       3 & 4 \end{pmatrix} \quad
则其转置为：
   A^T = \begin{pmatrix} 1 & 3 \\
                         2 & 4 \end{pmatrix} $$

In [4]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
A_transpose = A.T

print("原矩阵 A:\n", A)
print("转置矩阵 A^T:\n", A_transpose)

原矩阵 A:
 [[1 2]
 [3 4]]
转置矩阵 A^T:
 [[1 3]
 [2 4]]


### 矩阵的逆

#### 定义

一个可逆矩阵（或称为非奇异矩阵）是指一个方阵 $ A $ 存在一个矩阵 $ B $，使得 $ AB = BA = I $，其中 $ I $ 是单位矩阵。在这种情况下，我们称 $ B $ 为 $ A $ 的逆矩阵，通常记作 $ A^{-1} $。



#### 性质

1. 唯一性: 若矩阵 $ A $ 可逆，则其逆矩阵 $ A^{-1} $ 唯一。
2. 逆的乘法: $ (AB)^{-1} = B^{-1} A^{-1} $。
3. 逆的转置: $ (A^T)^{-1} = (A^{-1})^T $。

#### 例子

$$ A = \begin{pmatrix} 4 & 7 \\
                       2 & 6 \end{pmatrix} \quad
   计算行列式判断其是否可逆：
   \text{det}(A) = 4 \cdot 6 - 7 \cdot 2 = 24 - 14 = 10 \neq 0
                       $$

行列式不为零，矩阵 $ A $ 可逆。

$$ A^{-1} = \frac{1}{\text{det}(A)} \begin{pmatrix} d & -b \\
                                                    -c & a \end{pmatrix} 
          = \frac{1}{10} \begin{pmatrix} 6 & -7 \\
                                        -2 & 4 \end{pmatrix} 
          = \begin{pmatrix} 0.6 & -0.7 \\
                           -0.2 & 0.4 \end{pmatrix} $$

In [2]:
import numpy as np

A = np.array([[4, 7], [2, 6]])
A_inv = np.linalg.inv(A)

print("原矩阵 A:\n", A)
print("逆矩阵 A^{-1}:\n", A_inv)

原矩阵 A:
 [[4 7]
 [2 6]]
逆矩阵 A^{-1}:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
